Fix minor issue of cubes changing color in some scenes when grabbed
MixedRealityToolkit/MixedRealityToolkit-Unity pull request #545
Opened 2023-11-08 16:30 UTC by whebertML

Fixes: #544

2023-11-08 17:09 UTC, AMollis requested changes
@whebertML can you please add screen shots of the before and after changes

Also, please add more details to the PR description.  In particular I'm curious about the need for this change.

2023-11-08 17:11 UTC, AMollis commented on org.mixedrealitytoolkit.extendedassets/Materials/ObjectManipulationGrabbedLime.mat
If this is for samples only, please move these to the Sample project.

2023-11-08 20:18 UTC, keveleigh commented on org.mixedrealitytoolkit.extendedassets/Materials/ObjectManipulationGrabbedLime.mat
There are already two "Grabbed" materials in Extended Assets, and I'm not sure I agree they should be moved. This is basically the self-described purpose of this package: "This package offers additional assets helpful for example scenes"

2023-11-08 20:22 UTC, AMollis commented on org.mixedrealitytoolkit.extendedassets/Materials/ObjectManipulationGrabbedLime.mat
Makes sense thanks for setting my straight :)

2023-11-08 20:23 UTC, whebertML commented on org.mixedrealitytoolkit.extendedassets/Materials/ObjectManipulationGrabbedLime.mat
Done.

I originally made the new materials to sit alongside the other "grabbed" materials for some of those cubes that lives in extended assets.  Happy to just create new materials in the project itself without need to modify the package.  👍

2023-11-08 20:29 UTC, AMollis commented on org.mixedrealitytoolkit.extendedassets/Materials/ObjectManipulationGrabbedLime.mat
Sorry @whebertML .... I didn't realize that there were already Object Manipulator materials in here.   @keveleigh  set me straight.   Apologizes, you can undo your last commit, since there are already sample materials in the package.. I'm sorry for not realizing this. 

FWIW...why are sample materials in a UPM package?  What was the thinking here?

2023-11-08 20:30 UTC, whebertML commented
Before and after screen shots placed in issue description #544

2023-11-08 20:42 UTC, keveleigh commented on org.mixedrealitytoolkit.extendedassets/Materials/ObjectManipulationGrabbedLime.mat
> FWIW...why are sample materials in a UPM package? What was the thinking here?

100% open to revisiting this decision, but the idea was predicated around two things: sample distribution and prototyping enablement.

Under the assumption that we'd distribute our samples the same way we did in MRTK2 (as embedded samples in UPM packages, but trying to stay away from the idea of a samples-specific package, so we'd instead be embedding samples in their contextual packages), we realized we needed _some_ shared set of assets to reduce duplication. The approach of an "extended assets" package allowed us to avoid bloating those packages due to embedded sample assets and instead prompt the user to install this "extended assets" package when they imported the samples.

Secondarily, we thought it could be useful to build up a set of semi-polished visual components that could be used in prototyping scenarios, without bloating the "standard assets" package and without requiring the prototyper to import all the samples into their local project.

That's my recollection at least 😅

2023-11-08 22:07 UTC, whebertML commented on org.mixedrealitytoolkit.extendedassets/Materials/ObjectManipulationGrabbedLime.mat
@AMollis @keveleigh   Materials moved back to extendedassets

2023-11-09 17:52 UTC, AMollis approved these changes

2023-11-09 17:53 UTC, AMollis commented
/azp run

2023-11-10 16:22 UTC, whebertML commented
/azp run

2023-11-10 20:47 UTC, merged