Made Bound Controls Overridable And Updated Changelog
MixedRealityToolkit/MixedRealityToolkit-Unity pull request #715
Opened 2024-04-04 06:21 UTC by HossamBasion

Made four functions in boundscontrol.cs protected virtual and updated changelog and package.json accordingly.

This is necessary for adding custom translation, rotation and scaling logic for bound controls behavior.

2024-04-05 23:24 UTC, marlenaklein-msft requested changes

2024-04-05 23:24 UTC, marlenaklein-msft commented on org.mixedrealitytoolkit.spatialmanipulation/CHANGELOG.md
> -## [3.2.0-development] - 2024-03-20
please add a new section for 3.2.1 and add a bullet point to the added section to describe the change (can look to other package's change logs for example)

2024-04-05 23:24 UTC, marlenaklein-msft commented on org.mixedrealitytoolkit.spatialmanipulation/BoundsControl/BoundsControl.cs
> -        internal void OnHandleSelectExited(BoundsHandleInteractable handle, SelectExitEventArgs args)
protected virtual internal? BoundsHandleInteractable needs to be able to access this

2024-04-05 23:24 UTC, marlenaklein-msft commented on org.mixedrealitytoolkit.spatialmanipulation/BoundsControl/BoundsControl.cs
> -        internal void OnHandleSelectEntered(BoundsHandleInteractable handle, SelectEnterEventArgs args)
protected virtual internal?

2024-04-05 23:24 UTC, marlenaklein-msft commented on org.mixedrealitytoolkit.spatialmanipulation/BoundsControl/BoundsControl.cs
> -        internal void OnHandleSelectEntered(BoundsHandleInteractable handle, SelectEnterEventArgs args)
does it compile with just protected virtual?

2024-04-05 23:53 UTC, marlenaklein-msft submitted a review, later dismissed

2024-04-05 23:57 UTC, marlenaklein-msft commented
/azp run

2024-04-06 04:35 UTC, marlenaklein-msft commented
/azp run

2024-04-06 04:35 UTC, marlenaklein-msft approved these changes

2024-04-06 05:01 UTC, merged

2024-04-16 15:59 UTC, AMollis commented
@HossamBasion I need to review this change.  I'm not sure this is best solution for adding custom translation, rotation and scaling logic for bound controls behavior. 

I would like to see something similar to how we handle customization in the object manipulation behavior.


I'm going to review this and open bugs/issues as needed.